### ISSUE TITLE
Double allocating main and root moc?

### ISSUE THREAD

**Issue by YoonLee** [albertodebortoli/Skopelos#19]
Hi, first of all, great code you provide. 

By looking at the code at `CoreDataStack.swift` class, `init` which calls the `initialize` method at the end. Both of method creates the main and root contexts. Perhaps, designated initializer initializes the global variable, but I don't understand the reason `initialize` method calls again. Is there any reason?

**Comment by albertodebortoli** [comment]
Hi @YoonLee, thanks for this, you are right in pointing out that the code could avoid the repetition.

```
mainContext = NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType)
rootContext = NSManagedObjectContext(concurrencyType: .privateQueueConcurrencyType)
```

must stay in the init otherwise you'd get

```
Property 'self.mainContext' not initialized at super.init call
Property 'self.rootContext' not initialized at super.init call
```

Probably the reason why `initialize` re-creates the MOCs was because it is called by `nukeStore` too.

One might be tempted to change the properties to be explicit unwraps but... that wouldn't be nice since they come from the `CoreDataStackProtocol` and I think it's best to keep them as they are, i.e.

```
var mainContext: NSManagedObjectContext { get set }
var rootContext: NSManagedObjectContext { get set }
```

I think a decent way to solve it is #20 :) Any thoughts?
